backend:
  apiUrl: "http://192.168.0.101:8000/backend/v1/"

institution:
  name: "Stealthy"
  description: "Web application for secure sharing sensitive information"

pagination:
  perPageLimit: 6

routing:
  baseUrl: "stealthy/ui"
